### ISSUE TITLE
bug: 'pip install kaskada' fails on Vertex AI notebook. (runs fine on Colab)

### ISSUE THREAD

**Issue by stinkymatt** [kaskada-ai/kaskada#233]
**Description**
Running '!pip install kaskada' fails in a Vertex AI notebook with the following:

```
Installing collected packages: pyarrow, protobuf, html5lib, grpcio, elementpath, cssselect, pynacl, domonic, grpcio-status, pygithub, kaskada
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 11.0.0
    Uninstalling pyarrow-11.0.0:
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'RECORD'
Consider using the `--user` option or check the permissions.

```

**To Reproduce**
1. Create a new Vertex AI notebook, create a cell, type: "!pip install kaskada", run the cell

**Actual Behavior**
The installation fails with the error given above. Attempts to use kaskada after the failure give: ModuleNotFoundError: No module named 'kaskada'

**Expected Behavior**
A successful installation of the package as occurs in other environments. (I have tested both Colab and an Intel MBP)

**Additional context**
This was a Managed Runtime Vertex AI Notebook on a n1-standard-2 instance in gcp:us-central1

**Relevant Logs / Links**
[vertexpipfail.pdf](https://github.com/kaskada-ai/kaskada/files/11265798/vertexpipfail.pdf)

**Comment by therapon** [comment]
Any instruction that you can share on how you got to a collab inside Vertex AI? That would help me try it out but also inspect the setup and see how it differs from vanilla Collab. 


I have not used Vertex AI before :)

**Comment by therapon** [comment]
The file would be great. 

I think there is a free tier for Vertex AI so let me sign up and poke around a bit and see.

**Comment by kevinjnguyen** [comment]
@therapon do you have an update on this? I've gone ahead and assigned you to this.

**Comment by therapon** [comment]
I had a chance to setup an account and try it on a notebook in Google Cloud. This is just a jupyter notebook created from Vertex AI -> Workbench 

I did not call or use any of VertexAI's APIs :) 

The cells in order are 

```
pip install kaskada --user
```

The extra `--user` argument installs packages in the user's home directory. I believe the error that you saw was because without the `--user` `pip` will attempt to install in the global OS location. The setup on the Google Cloud machine does not allow the user access to that global location.


From there I took the same steps as the "Getting started guide" 


```
from kaskada.api.session import LocalBuilder

session = LocalBuilder().build()
```

```
from kaskada import table

table.create_table(
  # The table's name
  table_name = "Purchase",
  # The name of a column in your data that contains the time associated with each row
  time_column_name = "purchase_time",
  # The name of a column in your data that contains the entity key associated with each row
  entity_key_column_name = "customer_id",
)
```

I then uploaded the file from https://drive.google.com/uc?export=download&id=1SLdIw9uc0RGHY-eKzS30UBhN0NJtslkk

Then, 

```
table.load(table_name = "Purchase", file = "purchases_sorted.parquet")
```

```
%load_ext fenlmagic
```

```
%%fenl
Purchase
```


The screenshots below are in order so together they make up the complete view of my notebook. 


![image](https://github.com/kaskada-ai/kaskada/assets/284529/cb7f355a-d393-4587-beea-b1d867994cac)

![image](https://github.com/kaskada-ai/kaskada/assets/284529/2c60e9bf-5e32-47e3-8070-7f4f94d9e4fb)

![image](https://github.com/kaskada-ai/kaskada/assets/284529/88fa6599-f3b2-44e3-b425-beac02cd7e8d)

**Comment by epinzur** [comment]
make sure to add solution to docs
