### ISSUE TITLE
bug: Empty query results in Jupyter

### ISSUE THREAD

**Issue by kerinin** [kaskada-ai/kaskada#259]
**Description**
Running through a user study in vanilla Jupyter the data tab wasn't rendered in Jupyter. Other tabs (schema, details, etc) were shown, but not the data. Additionally, the response object's `dataframe` attribute was `None`.

**Comment by kevinjnguyen** [comment]
@kerinin do you have any additional information to reproduce this bug? The expected behavior for a query producing no results is to render a data frame with 0 rows. Something like this is the expected user experience:

<img width="609" alt="Screenshot 2023-05-05 at 11 13 47 AM" src="https://user-images.githubusercontent.com/15032894/236511587-62e6ea10-3d75-4f4f-8378-ad7e81b2cf39.png">

**Comment by kevinjnguyen** [comment]
This is no longer a problem. Verified in the latest ecommerce using the latest kaskada version.
