### ISSUE TITLE
feat: Return some message to tell the user that the fenlmagic extension loaded successfully

### ISSUE THREAD

**Issue by epinzur** [kaskada-ai/kaskada#305]
**Summary**
I'd like the fenlmagic extension to output something when it loads successfully.

```
%load_ext fenlmagic
```
(currently returns nothing)

**Is your feature request related to a problem? Please describe.**
I watched a user get very confused when there was no output after loading the extension. I think there will be other users that feel the same.

**Use Case**
Reduce confusion for new users of jupyter & kaskada.

**Describe the solution you'd like**
on succesful load of the extension, return a response like `fenlmagic extension loaded.` 

**Describe alternatives you've considered**

**Comment by epinzur** [comment]
found when helping Cordell Hayes from Datastax support team with our getting started tutorial via zoom

**Comment by kevinjnguyen** [comment]
If you believe this to be a bug, please update the description to match the [Bug Issue Template](https://github.com/kaskada-ai/kaskada/issues/new?assignees=&labels=bug&template=bug_report.md&title=bug%3A+...).

This is more a feature request than a bug, but I am open to a discussion/feature request to add additional feedback that the extension is loaded successfully. 

In your example, your Jupyter Notebook cell is running: `%load_ext fenlmagic`. This reads: "Call the single line magic `load_ext` and load the extension called `fenlmagic`". In the Jupyter Notebook, if this cell successfully ran to completion (the execution count went up), then the magic extension is loaded. If there was a failure to load the magic extension, then an error or exception would have been raised. Since no error or exception was raised and the `loadext` line magic completed successfully, the `fenlmagic` extension is loaded.

**Comment by epinzur** [comment]
I know how this works, but I watched a user get very confused that there was no output on a successful load of the extension. I suspect there are other users that will feel the same.

Is it possible to return output on successful load of the extension?
