### ISSUE TITLE
bug: loading file that dne returns internal error

### ISSUE THREAD

**Issue by jordanrfrazier** [kaskada-ai/kaskada#98]
**Description**
using `LoadData` to load an input file to a table returns an internal error when the file does not exist instead of a user error

**To Reproduce**
```
import kaskada.table

kaskada.table.create_table('transactions', 'transaction_time', 'id')
kaskada.table.load('transactions', <file_that_does_not_exist>')

**Actual Behavior**
```
Exception: An error occurred in your request.
	Error Code: INTERNAL
	Error Message: internal error
Details: 
```

**Expected Behavior**
```
Error: File at path <x> does not exist.
```

**Comment by kevinjnguyen** [comment]
Thanks for reporting this bug @jordanrfrazier. This was actually fixed in a subsequent PR and I've attached screenshots of the working implementation with different variations of loading the local file. 

<img width="1082" alt="Screenshot 2023-05-08 at 4 00 33 PM" src="https://user-images.githubusercontent.com/15032894/236934073-b21a6923-a2cd-4fb3-9640-225f6c044eb3.png">
<img width="887" alt="Screenshot 2023-05-08 at 4 01 37 PM" src="https://user-images.githubusercontent.com/15032894/236934291-1654ac53-a344-4d5c-a100-09bd0f236bd6.png">
<img width="898" alt="Screenshot 2023-05-08 at 4 01 49 PM" src="https://user-images.githubusercontent.com/15032894/236934324-dd346b0a-036c-40f1-b3fd-3d6f30573336.png">

I'll go ahead and close this issue now. Please re-open/file another issue if you see this issue again.
